name: Publish Canary

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: CI
    uses: jcmtallon/eslint-config-glamping/.github/workflows/ci.yml@main

  canary-release:
    name: Publish canary release
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/yarn-install
      - uses: ./.github/actions/gpr-auth
        with:
          token: ${{ github.token }}
      - run: |
          lerna publish \
            --dist-tag next \
            --exact \
            --force-publish \
            --ignore-prepublish \
            --ignore-scripts \
            --no-git-tag-version \
            --no-push \
            --yes \
            "$(cat lerna.json | jq -r .version)-canary.${GITHUB_SHA::7}"