name: Publish Release

on:
  push:
    tags:
      - v**

jobs:
  ci:
    name: CI
    uses: jcmtallon/eslint-config-glamping/.github/workflows/ci.yml@main

  publish-release:
    name: Release
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/yarn-install
      - uses: ./.github/actions/gpr-auth
        with:
          token: ${{ github.token }}
      - name: Publish package
        run: yarn lerna publish from-git -y
      - name: Generate changelog
        env:
          GITHUB_AUTH: ${{ github.token }}
        run: |
          export CHANGELOG_FROM="$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)"
          export CHANGELOG_TO="v$(cat lerna.json | jq -r .version)"
          npx -q lerna-changelog --from "$CHANGELOG_FROM" --to "$CHANGELOG_TO" > CHANGELOG.md
          cat CHANGELOG.md
      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ github.token }}
          bodyFile: CHANGELOG.md